### ISSUE TITLE
请问vue2版本 修改移动端适配方案 后 main.js 中引入的amfe-flexible是否多余?

### ISSUE THREAD

**Issue by YOOYY** [sunniejs/vue-h5-template#108]
如题

**Comment by fonghehe** [comment]
因为有人是需要一套网页在pc、移动跨端使用的，单纯用postcss会因为移动端的rootvalue导致组件很大

**Comment by YOOYY** [comment]
如果是rem的适配方案的话,postcss插件和amfe-flexible当然都需要用到
但是本项目vue2分支中不是把适配方案改成vm了嘛,所以这个文件是不是可以删掉? 
我想删除的原因是 因为根节点fontsize的不同导致行高不同,最终导致我在chrome中看到的排版样式与手机上的排版有些差异
