### ISSUE TITLE
request.js的坑。。。

### ISSUE THREAD

**Issue by lhshin** [sunniejs/vue-h5-template#11]
// respone拦截器
service.interceptors.response.use(
  response => {
    Toast.clear()
    const res = response.data
    if (res.status && res.status !== 200) { // **这里应该判断response.status**
      // 登录超时,重新登录
      if (res.status === 401) {
        store.dispatch('FedLogOut').then(() => {
          location.reload()
        })
      }
      return Promise.reject(res || 'error')
    } else {
      return Promise.resolve(res)
    }
  },
  error => {
    Toast.clear()
    console.log('err' + error) // for debug
    return Promise.reject(error)
  }
)

**Comment by sunniejs** [comment]
@lhshin每个项目的逻辑不同，我这里判断的是后台返回的数据，我会在文档中做下强调！谢谢
