### ISSUE TITLE
横屏效果不友好

### ISSUE THREAD

**Issue by tkkcc** [sunniejs/vue-h5-template#114]
横屏时观感上整体放大，难以使用。

https://user-images.githubusercontent.com/17373509/211262176-0e4c8ec3-1f71-4909-8fcd-b9f691565470.mp4

**Comment by fonghehe** [comment]
要保证ipad等大移动端尺寸设备使用的话，建议限制一个宽度，要不比例会很不协调

**Comment by tkkcc** [comment]
只是手机横屏模式，没有涉及 "ipad等大移动端尺寸设备"。ionic的viewport更合理。

**Comment by wswmsword** [comment]
@tkkcc 你好，可以考虑使用 [postcss-mobile-forever](https://github.com/wswmsword/postcss-mobile-forever) 进行桌面端适配，我提供了适配之后的代码和在线演示，您可以查看。

- 使用 postcss-mobile-forever 进行桌面端适配的 vue-h5-template 代码：[*https://github.com/wswmsword/postcss-mobile-forever/tree/main/example/templates/vue-h5-template*](https://github.com/wswmsword/postcss-mobile-forever/tree/main/example/templates/vue-h5-template)
- 在线演示桌面端展示良好的 vue-h5-template：[*https://wswmsword.github.io/examples/templates/vue-h5-template*](https://wswmsword.github.io/examples/templates/vue-h5-template)
