### ISSUE TITLE
请问：微信浏览器更新部署客户端不更新咋解决呢

### ISSUE THREAD

**Issue by lirahalu** [sunniejs/vue-h5-template#115]
请问在微信浏览器里使用，每次更新部署后，客户端大部分都没有读取最新的文件，需要手动刷新浏览器才行，试过一些方法都没有效果，大家是怎么解决的呢

**Comment by xieshenace** [comment]
右上角刷新，这个是内置浏览器的问题，不是这个项目问题。可以百度看看，有解决方案。

**Comment by fonghehe** [comment]
可以打包的时候生成一个hash文件，隔段时间去对比一次
