### ISSUE TITLE
打包后提示Cannot read properties of undefined (reading 'inBrowser') 

### ISSUE THREAD

**Issue by xieshenace** [sunniejs/vue-h5-template#116]
`index.764643b1.js:258 
        
       TypeError: Cannot read properties of undefined (reading 'inBrowser')
    at Si (index.b582b681.js:2:13702)
    at index.b582b681.js:2:21829`

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/35596347/221080926-ec6b49bf-538e-4fe7-8b9e-78c70cecd943.png">

**Comment by fonghehe** [comment]
请提供一下复现步骤

**Comment by xieshenace** [comment]
已经升级了最新版本，比对了缺失文件，成功嘞。
