### ISSUE TITLE
请问下baseURL应该写在哪里

### ISSUE THREAD

**Issue by dizheyoulan** [sunniejs/vue-h5-template#117]
我按文档写在了axios里，
const service = axios.create({
  baseURL: 'http://abcd.com/', 
  withCredentials: true, 
  timeout: 5000, 
});
然而请求地址都指向本地
http://localhost:5173/api/login

**Comment by fonghehe** [comment]
控制台中本地的请求地址是不会改变的，但是内部的代理是会帮你代理到你的接口上，主要看接口生不生效，请求地址不代表请求的资源指向
