### ISSUE TITLE
main.js中引入的index.scss样式重复

### ISSUE THREAD

**Issue by liuzhibo0725** [sunniejs/vue-h5-template#13]
每个页面当中会出现多次index中的样式，而且先引入的index后引入的vant，但是index比vant优先级还要高

**Comment by sunniejs** [comment]
@liuzhibo0725 hello，你可以加我微信我们交流一下吗？优先级的问题，以及重复的问题，我想了解一下你的想法

**Comment by sunniejs** [comment]
已优化

**Comment by cjs12** [comment]
能分享下怎么优化的吗？或者说这问题的原因是什么。
我发现main.js中
```js
import '@/assets/css/index.scss'
```
会有重复引用的问题。
然后如果使用
```js
import '@/assets/css/variables.scss'
```
不仅没有重复引用，还能吧index.scss的样式引进去。
（业余前端，望解惑）

**Comment by cjs12** [comment]
针对此问题的优化：

![image](https://user-images.githubusercontent.com/36249835/84742806-9b876480-afe3-11ea-883e-fe03a9286610.png)

* [index.scss引用两次优化链接](https://github.com/sunniejs/vue-h5-template/commit/842a3eb0c7ed07bf331a0fbb493938a78356361e#diff-0e893b3578ae3d5c8b98bac1c80756a7)

* [vue.config.js 中css配置](https://cli.vuejs.org/zh/config/#css-extract)
