### ISSUE TITLE
这个模版如果使用vant真的是巨坑!!!!!!!!!

### ISSUE THREAD

**Issue by hhhg99** [sunniejs/vue-h5-template#146]
1.showToast有的页面或者组件能用有的不能用,
 解决方案 main.ts 引入样式 import 'vant/lib/index.css';
 你以为解决了? 还是会有部分页面有问题,解决方案也很蠢,在页面写死一个不显示的vant组件<van-toast v-model:show="showPickr" style="padding: 0">
    </van-toast> 
 showPickr一直是false不显示
2.写的好好的,打包完发现页面vant的组件全tm阉割了一半,不得不说是真的坑

**Comment by blue-ling233** [comment]
引用库也是各种问题

**Comment by fonghehe** [comment]
你有问题你进群问啊，我不明白你写个大标题抛一堆问题都不愿意问一句是什么心态啊，朋友

**Comment by fonghehe** [comment]
不是每个框架都是极尽所能的，肯定会有缺陷，你可以提出问题，提issue，看到我会跟进，你凭啥上来就这坑那坑全坑啊，你contribute了吗，没有吧？？那你评价别人怎么如此得心应手啊
