### ISSUE TITLE
表示支持

### ISSUE THREAD

**Issue by shenzhenjinma** [sunniejs/vue-h5-template#17]
懒得自己集成，简单看了代码，小项目直接用你这个脚手架，支持一波 👍

**Comment by sunniejs** [comment]
thank you

**Comment by shenzhenjinma** [comment]
【自动回复】

    您好，这封是自动回复，我在看到您的邮件将第一时间回复，


    如有紧急问题请电话联系。


    
        注：若您收到此信息说明服务器已经接收到您的邮件
