### ISSUE TITLE
建议生成多页面配置

### ISSUE THREAD

**Issue by Zhengjian1** [sunniejs/vue-h5-template#26]
您好，非常感谢对本项目的支持，您可以在此留下你的宝贵意见和想法。
也可以添加作者微信：sunnie_song ,学习交流ლ(°◕‵ƹ′◕ლ)。

**Comment by fuerpeng** [comment]
![image](https://user-images.githubusercontent.com/24818415/122757227-f96f1c00-d2c9-11eb-9855-fb16c5cf45ea.png)
配置多页面，打包出来报错，请问还需要配置什么内容
