### ISSUE TITLE
npm run lint问题

### ISSUE THREAD

**Issue by Zswordcgf** [sunniejs/vue-h5-template#32]
您好，非常感谢对本项目的支持，您可以在此留下你的宝贵意见和想法。
也可以添加作者微信：sunnie_song ,学习交流ლ(°◕‵ƹ′◕ლ)。

执行npm run lint 操作后，会报错
rror: Cannot find module './env.undefined'
Require stack:
- /Users/zsword/Desktop/Code/vue-app/src/config/index.js
- /Users/zsword/Desktop/Code/vue-app/vue.config.js
- /Users/zsword/Desktop/Code/vue-app/node_modules/@vue/cli-shared-utils/lib/module.js
- /Users/zsword/Desktop/Code/vue-app/node_modules/@vue/cli-shared-utils/index.js
- /Users/zsword/Desktop/Code/vue-app/node_modules/@vue/cli-service/bin/vue-cli-service.js
Error: Cannot find module './env.undefined'
Require stack:
- /Users/zsword/Desktop/Code/vue-app/src/config/index.js
- /Users/zsword/Desktop/Code/vue-app/vue.config.js
- /Users/zsword/Desktop/Code/vue-app/node_modules/@vue/cli-shared-utils/lib/module.js
- /Users/zsword/Desktop/Code/vue-app/node_modules/@vue/cli-shared-utils/index.js
- /Users/zsword/Desktop/Code/vue-app/node_modules/@vue/cli-service/bin/vue-cli-service.js

感觉是不是config中的index.js文件配置需要修改某些数据

**Comment by sunniejs** [comment]
@Zswordcgf 问题已修复，感谢您的反馈
