### ISSUE TITLE
建议把node-sass改为sass

### ISSUE THREAD

**Issue by AntzyMo** [sunniejs/vue-h5-template#33]
您好，非常感谢对本项目的支持，您可以在此留下你的宝贵意见和想法。
也可以添加作者微信：sunnie_song ,学习交流ლ(°◕‵ƹ′◕ლ)。

建议把node-sass改为sass，解决下载问题

**Comment by cixiangtao** [comment]
> 您好，非常感谢对本项目的支持，您可以在此留下你的宝贵意见和想法。
> 也可以添加作者微信：sunnie_song ,学习交流ლ(°◕‵ƹ′◕ლ)。
> 
> 建议把node-sass改为sass，解决下载问题

应该是改成`dart-sass`才对，深度选择器由 `>>>`改为`::v-deep`即可。

**Comment by AntzyMo** [comment]
是的

**Comment by heavenly-zy** [comment]
> > 您好，非常感谢对本项目的支持，您可以在此留下你的宝贵意见和想法。
> > 也可以添加作者微信：sunnie_song ,学习交流ლ(°◕‵ƹ′◕ლ)。
> > 建议把node-sass改为sass，解决下载问题
> 
> 应该是改成`dart-sass`才对，深度选择器由 `>>>`改为`::v-deep`即可。

`/deep/`替换为`::v-deep`吧，貌似`>>>`还是兼容的

**Comment by fonghehe** [comment]
已替换成更加普适性的sass
