### ISSUE TITLE
请求后使用Toast回调返回上一页面会一直返回直到首页

### ISSUE THREAD

**Issue by warmup413** [sunniejs/vue-h5-template#34]
你好，请使用下面的模板创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

Browser version [浏览器类型和版本]
微信开发者工具

vue-h5-template version [vue-h5-template 版本]
 最新版

Vue version [Vue  版本]
 2.6.11

reappear link [重现链接]
 无

One-line summary  [描述问题]
在请求返回使用Toast回调返回上一页面会一直返回直到首页

![iShot2020-10-25 15 47 50](https://user-images.githubusercontent.com/32946251/97101561-8fba5600-16d9-11eb-806e-6389898e8d27.png)

Other comments [其他信息]

**Comment by sym134** [comment]
> 你好，请使用下面的模板创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。
> 
> Browser version [浏览器类型和版本]
> 微信开发者工具
> 
> vue-h5-template version [vue-h5-template 版本]
> 最新版
> 
> Vue version [Vue 版本]
> 2.6.11
> 
> reappear link [重现链接]
> 无
> 
> One-line summary [描述问题]
> 在请求返回使用Toast回调返回上一页面会一直返回直到首页
> 
> ![iShot2020-10-25 15 47 50](https://user-images.githubusercontent.com/32946251/97101561-8fba5600-16d9-11eb-806e-6389898e8d27.png)
> 
> Other comments [其他信息]

**Comment by fonghehe** [comment]
不建议这样写，关闭和后退不存在先后关系

**Comment by fonghehe** [comment]
不建议这样写，关闭和后退不存在先后关系
