### ISSUE TITLE
如何在vue页面里修改title标题

### ISSUE THREAD

**Issue by hugeng1979** [sunniejs/vue-h5-template#36]
首先，非常感谢你的项目。让我从vue新手能开始简单的写页面了。
有个问题想咨询一下，如何在类似about.vue里，修改最外面的title。

 path: '/about',
        name: 'About',
        component: () => import('@/views/home/about'),
        meta: { title: '关于我', keepAlive: false }
这里的title配置不起作用。

**Comment by hugeng1979** [comment]
解决了。我在router/index.js 增加了

const defaultTitle = '默认 title'
router.beforeEach((to, from, next) => {
  document.title = to.meta.title ? to.meta.title : defaultTitle
  next()
})

**Comment by sunniejs** [comment]
感谢您的使用，希望能为我的项目提供更多的意见和使用建议，为他人提供宝贵的意见，比心
