### ISSUE TITLE
执行stage，走的是env.production.js什么原因

### ISSUE THREAD

**Issue by liuzhibo0725** [sunniejs/vue-h5-template#37]
您好，非常感谢对本项目的支持，您可以在此留下你的宝贵意见和想法。
也可以添加作者微信：sunnie_song ,学习交流ლ(°◕‵ƹ′◕ლ)。

**Comment by txu-NO1** [comment]
我也遇到了同样的问题，有人可以回答一下吗

**Comment by txu-NO1** [comment]
> 我也遇到了同样的问题，有人可以回答一下吗

vue-h5-template/.env.staging 
中的环境变量没改成staging

**Comment by sunniejs** [comment]
@txu-NO1 谢谢您的反馈，该问题已经修复
