### ISSUE TITLE
是否会升级vant到3.0版本？

### ISSUE THREAD

**Issue by hugeng1979** [sunniejs/vue-h5-template#41]
您好，非常感谢对本项目的支持，您可以在此留下你的宝贵意见和想法。
也可以添加作者微信：sunnie_song ,学习交流ლ(°◕‵ƹ′◕ლ)。

**Comment by sunniejs** [comment]
@hugeng1979 vant可以自己npm 安装你想要的版本，后面可能会考虑升级vant和vue
