### ISSUE TITLE
页面缓存keepAlive代码错误

### ISSUE THREAD

**Issue by fefisher** [sunniejs/vue-h5-template#42]
Browser version [Chrome 87]
 

vue-h5-template version [vue-h5-template 版本]
 

Vue version [Vue  2.6.12]
 

code
```
     <keep-alive v-if="$route.meta.keepAlive">
        <router-view></router-view>
      </keep-alive>
      <router-view v-else></router-view>
```
应该写成
```
     <keep-alive>
        <router-view  v-if="$route.meta.keepAlive"></router-view>
      </keep-alive>
      <router-view v-else></router-view>
```

**Comment by fefisher** [comment]
推荐使用以下方式
```javascript
 <keep-alive :exclude="['a','b']">
        <router-view></router-view>
 </keep-alive>
```

**Comment by Adaer** [comment]
> Browser version [Chrome 87]
> 
> vue-h5-template version [vue-h5-template 版本]
> 
> Vue version [Vue 2.6.12]
> 
> code
> 
> ```
>      <keep-alive v-if="$route.meta.keepAlive">
>         <router-view></router-view>
>       </keep-alive>
>       <router-view v-else></router-view>
> ```
> 
> 应该写成
> 
> ```
>      <keep-alive>
>         <router-view  v-if="$route.meta.keepAlive"></router-view>
>       </keep-alive>
>       <router-view v-else></router-view>
> ```
v-else 会出问题的，不在一个块内
      <keep-alive>
        <router-view v-if="$route.meta.keepAlive"/>
      </keep-alive>
      <router-view v-if="!$route.meta.keepAlive" />

**Comment by zhangyuanliang** [comment]
```
<keep-alive>
  <router-view  v-if="$route.meta.keepAlive"></router-view>
</keep-alive>
<router-view   v-if="!$route.meta.keepAlive"></router-view>
```
