### ISSUE TITLE
关于 eslint prettier vetur 这三个工具的配置文章“催更”

### ISSUE THREAD

**Issue by aisen-cai** [sunniejs/vue-h5-template#44]
﻿﻿
<img width="1218" alt="图片" src="https://user-images.githubusercontent.com/19338152/111071127-aa1d9080-850f-11eb-8755-93db0f76f3e4.png">

**Comment by Adaer** [comment]
如果使用 prettier ，你不介意 格式化后 标签内的属性都在一行 就可以使用。
对于属性换行，大部分人都是支持例如属性有3个以上时 换行，但是使用prettier 后，会变成一行显示
