### ISSUE TITLE
IE还是有点问题

### ISSUE THREAD

**Issue by CNLJ** [sunniejs/vue-h5-template#5]
开本地环境运行，ie打开，报错了，build出来ie10还是有些问题，你的demo地址是正常的

**Comment by xiang473535976** [comment]
vuex requires a Promise polyfill in this browser      同样  ie报错

**Comment by xiang473535976** [comment]
vuex requires a Promise polyfill in this browser 同样 ie报错      本地环境运行   build编译发布 没问题

**Comment by sunniejs** [comment]
@CNLJ @xiang473535976 修复vuex requires a Promise polyfill in this browser报错，可手动将main.js
`//  IE 兼容
import '@babel/polyfill'`
放到最上排
ie11可正常运行
