### ISSUE TITLE
一直提示跨域

### ISSUE THREAD

**Issue by 2kGeekc** [sunniejs/vue-h5-template#72]
接口一直跨域，但是接口在其他项目是正常运行的

**Comment by godloveBiya** [comment]
我也遇到这个问题了

**Comment by 2kGeekc** [comment]
> 我也遇到这个问题了

看源码发现是axios设置了withCredentials参数, 之前我们后端处理跨域之设置Access-Control-Allow-Origin请求头就行了, 因为设置了withCredentials参数还需要返回Access-Control-Allow-Credentials 头, 直接去request.js文件修改axios的withCredentials参数为false即可

**Comment by 2kGeekc** [comment]
看源码发现是axios设置了withCredentials参数, 之前我们后端处理跨域之设置Access-Control-Allow-Origin请求头就行了, 因为设置了withCredentials参数还需要返回Access-Control-Allow-Credentials 头, 直接去request.js文件修改axios的withCredentials参数为false即可

**Comment by godloveBiya** [comment]
解决了
