### ISSUE TITLE
项目启动报错，麻烦帮忙看下是否有问题问题

### ISSUE THREAD

**Issue by li-songyang** [sunniejs/vue-h5-template#92]
下载源文件，npm install ，npm run serve
控制包报错 

Syntax Error: TypeError: Cannot read property 'styles' of undefined

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.

谢谢

**Comment by fonghehe** [comment]
别用npm，用yarn

**Comment by li-songyang** [comment]
邮件已收到，谢谢~
