### ISSUE TITLE
mock如何启动

### ISSUE THREAD

**Issue by MssText** [sunniejs/vue-h5-template#93]
<img width="1254" alt="image" src="https://user-images.githubusercontent.com/49203535/185543221-83200c6f-6303-444d-9f68-3376e1f22ec3.png">

**Comment by vintonHuang** [comment]
可以看一下你的mock的vite插件服务，是否是正常开启的，然后看下你是否有配置这个api的mock

**Comment by MssText** [comment]
> 可以看一下你的mock的vite插件服务，是否是正常开启的，然后看下你是否有配置这个api的mock

就是这个模版 我什么都没有改动，mock功能就是异常的

**Comment by MssText** [comment]
> 

插件服务是正常开启的 api mock也有 因为就是作者提供的模版中的示例
